<?php
  function pet_menu() {
    $items = array();
    $items['Mazzy'] = array(
      'title' => 'Meet Mazzy!',
      'page callback' => 'meet_mazzy',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
  }

  function meet_mazzy() {
    $path = drupal_get_path('module', 'pet');
    $image = $path . '/Mazzy.jpg';
    $link = "<a href = 'https://en.wikipedia.org/wiki/Bulldog'>Wiki</a>";
    return "<p>My baby dog Mazzy Pooperini. She was an italian english bulldog ( see info at " . $link . "). Died March 2015.</p><br><img src='" . $image . "' class= 'mazzy'/>";
  }
